### ISSUE TITLE
[BUG] 11-bootstrap demo make error

### ISSUE THREAD

**Issue by jonyangx** [eunomia-bpf/bpf-developer-tutorial#102]
**Describe the bug**
make 11-bootstrap  demo error.

Finished release [optimized] target(s) in 0.10s
  GEN-SKEL bootstrap.skel.h
libbpf: elf: bootstrap_bpf is not a valid eBPF object file
Error: failed to open BPF object file: BPF object format invalid
make: *** [Makefile:144: /root/opensource/bpf-developer-tutorial/src/11-bootstrap/.output/bootstrap.skel.h] Error 95

**To Reproduce**

1. Go to 'bpf-developer-tutorial/src/11-bootstrap'
2. Click on 'make'
3. See error

**Expected behavior**
......
warning: `blazesym` (lib) generated 26 warnings (run `cargo fix --lib -p blazesym` to apply 26 suggestions)
    Finished release [optimized] target(s) in 0.10s
  GEN-SKEL bootstrap.skel.h
libbpf: elf: bootstrap_bpf is not a valid eBPF object file
Error: failed to open BPF object file: BPF object format invalid
make: *** [Makefile:144: /root/opensource/bpf-developer-tutorial/src/11-bootstrap/.output/bootstrap.skel.h] Error 95
**Screenshots**

**Desktop (please complete the following information):**

* OS: [e.g. Windows]
Linux iZwz9gixb0fvl0px5nzzynZ 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
5.15.0-91-generic

**Additional context**
none

**Comment by yunwei37** [comment]
What's your clang or libbpf version? I cannot replicate that, sorry...

**Comment by jonyangx** [comment]
After update ubuntu linux kernel to 5.15.0-92-generic ,it run ok!
