### ISSUE TITLE
请问大佬，我这里案例23-http中的sockfilter程序为什么只显示了本地HTTP流量？

### ISSUE THREAD

**Issue by Nekotoxin** [eunomia-bpf/bpf-developer-tutorial#107]
按照[案例](https://eunomia.dev/tutorials/23-http/#compilation-and-execution)，启动了本地python echo服务器，并且执行`curl http://0.0.0.0:8000/`，sockfilter显示了从127.0.0.1:45228(src) -> 127.0.0.1:8000(dst)的数据传输：

<img width="542" alt="image" src="https://github.com/eunomia-bpf/bpf-developer-tutorial/assets/75596353/bc405d88-e21e-4861-9807-93c52b0a2245">

<img width="453" alt="image" src="https://github.com/eunomia-bpf/bpf-developer-tutorial/assets/75596353/57dc67e1-6a45-478b-b5c2-f77c80d9fc3f">

但是当`curl www.baidu.com`时，似乎没有反应？

<img width="1410" alt="image" src="https://github.com/eunomia-bpf/bpf-developer-tutorial/assets/75596353/895b23f6-eab7-4d4e-bf35-a6ad71ffe37e">

环境：debian 12.4, kernel version=6.1.0-17-amd64，其他按照教程

**Comment by Nekotoxin** [comment]
发现是默认在本地环回接口上监听（lo），改成eth0就可以监听外部的了

**Comment by haolipeng** [comment]
这个和dns的网络原理有关
curl http://0.0.0.0:8000/ 此时http请求包是走0.0.0.0地址的，也就是lo接口
如果你换成curl www.baidu.com，那么首先会把www.baidu.com解析成ip地址ip1，然后查找系统的路由表，查找到ip1应该从ensXX接口发送出去（这个口不可能是lo口）
