### ISSUE TITLE
使用eunomia时，可以自定义输出吗

### ISSUE THREAD

**Issue by Guncuke** [eunomia-bpf/bpf-developer-tutorial#120]
在做网络监测的时候，发现不自定义输出的话，IP地址是字节序，而且union组成的ipv4和ipv6无法控制二选一输出，只能用libbpf

**Comment by Officeyutong** [comment]
> 在做网络监测的时候，发现不自定义输出的话，IP地址是字节序，而且union组成的ipv4和ipv6无法控制二选一输出，只能用libbpf

Directly use libeunomia and registered a custom output handler

**Comment by Officeyutong** [comment]
> > 在做网络监测的时候，发现不自定义输出的话，IP地址是字节序，而且union组成的ipv4和ipv6无法控制二选一输出，只能用libbpf
> 
> Directly use bpf-loader-rs and registered a custom output handler. See https://github.com/eunomia-bpf/eunomia-bpf/blob/cc60a808ac2e5d927b13e48f9272f814f91552b1/bpf-loader-rs/bpf-loader-lib/src/export_event/tests/mod.rs#L48 for details

**Comment by Guncuke** [comment]
thanks
