### ISSUE TITLE
[TYPO] 在教程有错误

### ISSUE THREAD

**Issue by PPKunOfficial** [eunomia-bpf/bpf-developer-tutorial#127]
在[GitHub 模板](https://eunomia.dev/zh/tutorials/1-helloworld/#github-ebpf)里，cilium/ebpf框架应是基于go语言的

**Comment by yunwei37** [comment]
确实，看起来是个 typo

**Comment by yunwei37** [comment]
Would be appreciated if someone can submit a PR to fix that (lol
