### ISSUE TITLE
[FEATURE] 创建 eBPF 开发知识库，使用其他知识库实现进行交互式的学习

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/bpf-developer-tutorial#14]
see:

- https://github.com/arc53/DocsGPT
- https://github.com/eunomia-bpf/docsgpt-backend

需要：

- 通过 Github Pages 和后端部署（可以用 serverless 或者别的方案）直接通过网页使用，可以交互式的提问和回答问题；
- 和 Github Actions 进行持续集成

会不会有更好的方案呢？

**Comment by Officeyutong** [comment]
Closes as https://github.com/eunomia-bpf/ebpf-knowledge-base done. Subsequent issues can be opened at ebpf-knowledge-base repo
