### ISSUE TITLE
[BUG]40-mysql-NotWork

### ISSUE THREAD

**Issue by xuebatian** [eunomia-bpf/bpf-developer-tutorial#152]
**Describe the bug**
--
```
My OS version is 
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble
```
--
```
My Mysql version is  8.0.40
root@VM-12-4-ubuntu:~# mysql --version
mysql  Ver 8.0.40-0ubuntu0.24.04.1 for Linux on x86_64 ((Ubuntu))
root@VM-12-4-ubuntu:~# 
```
-- 
i found two unexpected behavior

# number 1
this is no `uprobe:xx:dispatch_command` in my mysql binary
here is what i have in my mysql
```console
root@VM-12-4-ubuntu:~# bpftrace -l 'uprobe:/usr/sbin/mysqld:*dispatch_command*'
uprobe:/usr/sbin/mysqld:_Z16dispatch_commandP3THDPK8COM_DATA19enum_server_command
root@VM-12-4-ubuntu:~# echo 'uprobe:/usr/sbin/mysqld:_Z16dispatch_commandP3THDPK8COM_DATA19enum_server_command' | c++filt
uprobe:/usr/sbin/mysqld:dispatch_command(THD*, COM_DATA const*, enum_server_command)
root@VM-12-4-ubuntu:~# 
```

# number 2

the content of sql  printed is empty,when sql i executed is not empty

first of all,i choosed the most likely uprobe in number as my probe point

here is the result 
```console
Attaching 2 probes...
MySQL command executed by PID 1974646: 
Latency: 0 ms
MySQL command executed by PID 1974646: 
Latency: 0 ms
MySQL command executed by PID 1974646: 
Latency: 0 ms
MySQL command executed by PID 1974646: 
Latency: 0 ms
MySQL command executed by PID 1974646: 
Latency: 0 ms
MySQL command executed by PID 1974646: 
Latency: 0 ms
MySQL command executed by PID 1974646: 
Latency: 0 ms
```

**Additional context**

my bpftrace shell
```
#!/usr/bin/env bpftrace

// 跟踪 MySQL 中的 dispatch_command 函数
uprobe:/usr/sbin/mysqld:_Z16dispatch_commandP3THDPK8COM_DATA19enum_server_command
{
    // 将命令执行的开始时间存储在 map 中
    @start_times[tid] = nsecs;
    
    // 打印进程 ID 和命令字符串
    printf("MySQL command executed by PID %d: ", pid);
    
    // dispatch_command 的第三个参数是 SQL 查询字符串
    printf("%s\n", str(arg3));
}
uprobe:/usr/sbin/mysqld:_Z16dispatch_commandP3THDPK8COM_DATA19enum_server_command
{
    // 从 map 中获取开始时间
    $start = @start_times[tid];
    
    // 计算延迟，以毫秒为单位
    $delta = (nsecs - $start) / 1000000;
    
    // 打印延迟
    printf("Latency: %u ms\n", $delta);
    
    // 从 map 中删除条目以避免内存泄漏
    delete(@start_times[tid]);
}
```

**Comment by Officeyutong** [comment]
According to your symbol name `_Z16dispatch_commandP3THDPK8COM_DATA19enum_server_command`, (which demangles to `dispatch_command(THD*, COM_DATA const*, enum_server_command)`), you may need to access the union `COM_DATA const *` to get the sql statement. See source code https://github.com/mysql/mysql-server/blob/61a3a1d8ef15512396b4c2af46e922a19bf2b174/sql/sql_parse.cc#L1727 here for details

**Comment by xuebatian** [comment]
3q  you are my hero

**Comment by xuebatian** [comment]
<img width="646" alt="image" src="https://github.com/user-attachments/assets/1df14d03-8031-4494-9bbd-ed79299b9476">
you are my hero.

here is the new bpftrace 
#!/usr/bin/env bpftrace

// 定义 COM_QUERY_DATA 结构
struct COM_QUERY_DATA {
  const char *query;
  unsigned int length;
};

// 定义 COM_DATA 联合
union COM_DATA {
    struct COM_QUERY_DATA com_query;
    // 其他类型省略
};


// 跟踪 MySQL 中的 dispatch_command 函数
uprobe:/usr/sbin/mysqld:_Z16dispatch_commandP3THDPK8COM_DATA19enum_server_command
{
    // 将命令执行的开始时间存储在 map 中
    @start_times[tid] = nsecs;
    
    // 打印进程 ID 和命令字符串
    printf("MySQL command executed by PID %d: ", pid);
    
    // 获取第二个参数，注意这里是指针
    $com_data_ptr = (union COM_DATA *)arg1;

    // 提取 com_query 属性中的 query 字符串
    $query = str($com_data_ptr->com_query.query);

    // 打印 SQL 查询
    printf("SQL Query: %s\n", $query);
}
uprobe:/usr/sbin/mysqld:_Z16dispatch_commandP3THDPK8COM_DATA19enum_server_command
{
    // 从 map 中获取开始时间
    $start = @start_times[tid];
    
    // 计算延迟，以毫秒为单位
    $delta = (nsecs - $start) / 1000000;
    
    // 打印延迟
    printf("Latency: %u ms\n", $delta);
    
    // 从 map 中删除条目以避免内存泄漏
    delete(@start_times[tid]);
}
