### ISSUE TITLE
docker编译后 ecc或者ecli运行报错

### ISSUE THREAD

**Issue by heckerstone** [eunomia-bpf/bpf-developer-tutorial#17]
报错内容如下(执行命令为:sudo ./ecli run ./package.json )：
./ecli: error while loading shared libraries: libcrypto.so.3: cannot open shared object file: No such file or directory

**Comment by ocfox** [comment]
It seems that OpenSSL is missing, can you tell me which docker image or dockerfile are you using?

**Comment by ocfox** [comment]
`yunwei37/ebpm:latest` is no longer maintained, we will fix `ecli-x86_64` as soon as possible, before that you can use release or build ecli locally.

**Comment by yunwei37** [comment]
we should fix all docker commands in the tutorial and documents.

**Comment by duanhaowei** [comment]
> 报错内容如下(执行命令为:sudo ./ecli run ./package.json )： ./ecli: error while loading shared libraries: libcrypto.so.3: cannot open shared object file: No such file or directory

try to install openssl3 will fix the problem

**Comment by yunwei37** [comment]
Fix for new eunomia-bpf version.
