### ISSUE TITLE
libbpf: map '.rodata.str1.1': failed to create: Invalid argument(-22)

### ISSUE THREAD

**Issue by duanhaowei** [eunomia-bpf/bpf-developer-tutorial#18]
**Describe the bug**
in lession02 , 
i packing c code use  `./ecc hello.bpf.c`   
root@ro:~/ebpf# ls
```
ebpf  ecli         hello.bpf.o      llvm.sh       t1
ecc   hello.bpf.c  hello.skel.json  package.json
```
but when i use 
sudo ./ecli run ./package.json
```
arg: ./package.json
libbpf: map '.rodata.str1.1': failed to create: Invalid argument(-22)
libbpf: failed to load object 'hello_bpf'
libbpf: failed to load BPF skeleton 'hello_bpf': -22
failed to load skeleton
Error: BpfError("load and attach ebpf program failed")
```

**Desktop (please complete the following information):**
 cat /proc/version
`Linux version 5.4.0-109-generic (buildd@ubuntu) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022`

![image](https://user-images.githubusercontent.com/13497115/229663912-d2ffe26a-b704-4901-97e9-3976290e0e59.png)

and use readelf
![image](https://user-images.githubusercontent.com/13497115/229663511-9f5b429e-941d-4e24-8ca0-4e1e28f2a9fe.png)

is something wrong with my libbpf ? or clang-13?
according   #https://github.com/libbpf/bpftool/issues/27

**Comment by duanhaowei** [comment]
i got wrong Labels "bug" ,plz remove it.

**Comment by duanhaowei** [comment]
升级内核解决问题。

**Comment by LinkXSystem** [comment]
> 升级内核解决问题。

请问这个升级内核是指升级 linux 的内核吗？升级到哪一个版本？
