### ISSUE TITLE
[BUG]lesson 7 可编译但是无法运行。

### ISSUE THREAD

**Issue by duanhaowei** [eunomia-bpf/bpf-developer-tutorial#23]
**Describe the bug**

`root@master01:~/ebpf/les6# sudo ecli run ./package.json`

![image](https://user-images.githubusercontent.com/13497115/236425807-c4c15b84-c755-48b9-a287-6f612b69c6cc.png)
![image](https://user-images.githubusercontent.com/13497115/236425868-d88df88d-008a-42f6-a04b-3d986193210d.png)

我的代码
```
struct event7 {
 int pid;
 int ppid;
 int uid;
 int retval;
 bool is_exit;
 char comm[TASK_COMM_LEN];
};

struct {
 __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
 __uint(key_size, sizeof(u32));
 __uint(value_size, sizeof(u32));
} events SEC(".maps");

SEC("tracepoint/syscalls/sys_enter_execve")
int tracepoint__syscalls__sys_enter_execve(struct trace_event_raw_sys_enter* ctx)
{
 u64 id;
 pid_t pid, tgid;
 struct event7 event;
 struct task_struct *task;

 uid_t uid = (u32)bpf_get_current_uid_gid();
 id = bpf_get_current_pid_tgid();
 pid = (pid_t)id;
 tgid = id >> 32;

 event.pid = tgid;
 event.uid = uid;
 task = (struct task_struct*)bpf_get_current_task();
 event.ppid = BPF_CORE_READ(task, real_parent, tgid);
 bpf_get_current_comm(&event.comm, sizeof(event.comm));
 bpf_perf_event_output(ctx, &events, BPF_F_CURRENT_CPU, &event, sizeof(event));
 return 0;
}  
```

**To Reproduce**

使用lesson6的代码，课程1-6可以运行

![image](https://user-images.githubusercontent.com/13497115/231678689-9b92e940-fc63-4202-a479-b2d875bf2278.png)
![image](https://user-images.githubusercontent.com/13497115/231678770-8c4dfadd-d849-487f-8c18-1a3843cc0f18.png)
![image](https://user-images.githubusercontent.com/13497115/231678903-48d3f771-c6be-4fb9-9178-d8c09547ff95.png)

help me!!

**Comment by try-agaaain** [comment]
可以给出完整的错误信息吗，我在本地没有复现出这个错误

**Comment by duanhaowei** [comment]
> 可以给出完整的错误信息吗，我在本地没有复现出这个错误

抱歉，这几天在忙别的（开摆）回复迟了。  我发现问题出现在 Lesson 7 上而不是6  ，我修改一下issue。
 请问我还需要提供哪一些信息？

**Comment by try-agaaain** [comment]
.h文件和.c文件不建议合并，ecc在编译时需要从.h文件中获取导出信息。

**Comment by duanhaowei** [comment]
@try-agaaain   谢谢大神的回答，问题解决了。我对C语言不熟悉，请问可以指点一下您说的 `ecc在编译时需要从.h文件中获取导出信息。` 吗？
我的错误代码中既然吧h文件和c文件合并了，为什么还需要导出信息？

**Comment by yunwei37** [comment]
这是我们工具链的设计，需要从 .h 中获取需要输出到用户态的结构体信息。
