### ISSUE TITLE
[BUG] Execsnoop has redundant code

### ISSUE THREAD

**Issue by dierbei** [eunomia-bpf/bpf-developer-tutorial#44]
**Describe the bug**

When I was reading the code, I encountered very confusing things.

https://github.com/eunomia-bpf/bpf-developer-tutorial/blob/f1c9cba2c4ed33cba678064099650955ee0b0f62/src/7-execsnoop/README.md?plain=1#L60

The line of code above doesn't seem to do anything.

**Comment by yunwei37** [comment]
Thanks for reporting! It's my mistake...
