### ISSUE TITLE
[BUG] legacy map definitions in 'maps' section are not supported by libbpf v1.0+

### ISSUE THREAD

**Issue by Whaiy** [eunomia-bpf/bpf-developer-tutorial#75]
**load.sh err**
after build, runs crashed err output

**Screenshots**

`
src/29-sockops$ sudo ./load.sh
+ set -e
+ sudo mount -t bpf bpf /sys/fs/bpf/
+ sudo bpftool prog load bpf_sockops.o /sys/fs/bpf/bpf_sockop
libbpf: elf: legacy map definitions in 'maps' section are not supported by libbpf v1.0+
Error: failed to open object file`

**Desktop (please complete the following information):**

Debian 6.1.52-1 (2023-09-07) x86_64 GNU/Linux

**Comment by SirHao** [comment]
The code is out-date with map section declaration, see https://github.com/libbpf/libbpf/issues/272

**Comment by SirHao** [comment]
@Whaiy Hi, this section has been rewrite. Can you please fetch the lastest version and verify it?

**Comment by Whaiy** [comment]
thanks, that's work
