### ISSUE TITLE
在MacOS系统下使用docker跑helloworld报错 failed to find vmlinux BTF

### ISSUE THREAD

**Issue by ToviHe** [eunomia-bpf/bpf-developer-tutorial#81]
1、在MacOS下拉取了两个镜像，分别是 `ghcr.io/eunomia-bpf/ecc-aarch64:latest` 以及 `pull ghcr.io/eunomia-bpf/ecli-aarch64:latest`

2、首先通过命令 ```docker run -it -v `pwd`/:/src/ ghcr.io/eunomia-bpf/ecc-aarch64:latest``` ，执行如下：
```
(base) ➜  1-helloworld git:(main) docker run -it -v `pwd`/:/src/ ghcr.io/eunomia-bpf/ecc-aarch64:latest
ls: cannot access '/src/*.h': No such file or directory
INFO [ecc_rs::bpf_compiler] Compiling bpf object...
INFO [ecc_rs::bpf_compiler] Generating package json..
INFO [ecc_rs::bpf_compiler] Packing ebpf object and config into /src/package.json...
```

3、`ls` 查看
```
(base) ➜  1-helloworld git:(main) ls
README.md         README_en.md      minimal.bpf.c     minimal.bpf.o     minimal.skel.json package.json
```

4、随后通过命令 ```docker run -it -v `pwd`/:/src/ ghcr.io/eunomia-bpf/ecli-aarch64:latest  run /src/package.json```，执行如下：
```
(base) ➜  1-helloworld git:(main) docker run -it -v `pwd`/:/src/ ghcr.io/eunomia-bpf/ecli-aarch64:latest  run /src/package.json
arg: /src/package.json
failed to find vmlinux BTF. please provide btf file with env BTF_FILE_PATH.
Error: BpfError("load and attach ebpf program failed")
```

帮忙看看是Mac下不支持吗？

**Comment by Officeyutong** [comment]
If the docker daemon you use was based on virtual machine, you may need to pay attention to the directory that mounts into the container (`-v xxx:yyy`). See https://docs.docker.com/desktop/settings/mac/#file-sharing for details

**Comment by ToviHe** [comment]
后面我没有尝试去使用docker方式了，我采用multipass启动ubuntu虚拟机方式成功运行起来了

**Comment by yunwei37** [comment]
一般来说 MacOS 不支持的吧

**Comment by Officeyutong** [comment]
> 一般来说 MacOS 不支持的吧

docker for macos are is based on linux virtual machines, similar to docker toolbox on windows
