### ISSUE TITLE
1-helloworld中，【./ecc minimal.bpf.c】命令执行完之后提示找不到命令【sudo: ./ecc：找不到命令

### ISSUE THREAD

**Issue by HuAn28** [eunomia-bpf/bpf-developer-tutorial#87]
、
![Uploading 1.png…]()

**Comment by Officeyutong** [comment]
You may download ecc from https://github.com/eunomia-bpf/eunomia-bpf/releases/tag/v1.0.19

**Comment by HuAn28** [comment]
> 您可以从 https://github.com/eunomia-bpf/eunomia-bpf/releases/tag/v1.0.19 下载 ecc

thanks!
