### ISSUE TITLE
阅读 ebpf 中文入门指南：https://www.modb.pro/db/391570 （1h）[BUG]

### ISSUE THREAD

**Issue by MiterV1** [eunomia-bpf/bpf-developer-tutorial#90]
阅读 ebpf 中文入门指南：https://www.modb.pro/db/391570
连接挂了

**Comment by yunwei37** [comment]
也许可以用这篇?
https://www.ebpf.top/post/ebpf_intro/
或者有更好的推荐，也可以发出来讨论一下?

（如果方便的话，可以帮我们提一个 pr，把旧的 404 了的链接替换掉啦

**Comment by yunwei37** [comment]
Fixed.
